### ISSUE TITLE
authorized_doorbots is returning empty now, API changed?

### ISSUE THREAD

**Issue by tylerrbrown** [KoenZomers/RingSnapshotDownload#1]
....or do I not have something configured correctly?

Unhandled exception. System.Net.WebException: The remote server returned an error: (404) Not Found.
   at KoenZomers.Ring.SnapshotDownload.Program.<Main>(String[] args)

**Comment by KoenZomers** [comment]
I managed to reproduce this issue once. Seems like if you haven't retrieved a snapshot from your Ring device in a while, Ring no longer has one on file. When requesting the Ring API a new one to be taken, it takes some time before it successfully can do so. In the meantime it will return a 404 not found.

I've made several changes to the code to be able to handle this situation, such as adding a retry when this happens. See the release notes of [version 1.0.1.0](https://github.com/KoenZomers/RingSnapshotDownload/releases/tag/1.0.1.0) for all the details on what has changed.

Can you give it a try with this new version and see if this resolves this issue for you?

**Comment by KoenZomers** [comment]
Closing as no feedback has been received
