### ISSUE TITLE
[BUG]  No devices found

### ISSUE THREAD

**Issue by afaq-khan** [KoenZomers/RingSnapshotDownload#2]
**Describe the bug**
When running RingSnapshotDownload.exe with username, password and list parameters, the result is: 

Connecting to Ring services
Authenticating using refresh token from previous session
Retrieving all devices... Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at KoenZomers.Ring.SnapshotDownload.Program.Main(String[] args)
   at KoenZomers.Ring.SnapshotDownload.Program.<Main>(String[] args) 

Seems like `await session.GetRingDevices();` is returning null instead of devices

The issue seems to be caused by the API:

Unexpected character encountered while parsing value: {. Path 'stickup_cams[0].motion_snooze', line 1, position 8408.

`"motion_snooze": {
                "scheduled": true
            },`

**To Reproduce**
1. Run RingSnapshotDownload.exe -username xxx@xxx.xxx -password xxxxxx -list

**Expected behavior**
No error, snapshot downloaded

**Screenshots**
![89105176-2222c480-d41f-11ea-9d3b-4953140adf38](https://user-images.githubusercontent.com/42817332/89126408-bc4d4000-d4e5-11ea-8f1c-e3157d6c7fef.png)

**Versions (please complete the following information):**
- OS: Windows 10 2004
- RingSnapshotDownload: v1.0.2

**Comment by KoenZomers** [comment]
Sorry haven't noticed your comment before. As this is already a long time ago, please let me know in case you're still struggling with this and want to get it to work and I can help you to troubleshoot it.

**Comment by KoenZomers** [comment]
Closing as no further feedback has been received
