### ISSUE TITLE
[BUG] OS X Binary in 1.0.2.0 is not a correct binary

### ISSUE THREAD

**Issue by rogerheykoop** [KoenZomers/RingSnapshotDownload#3]
**Describe the bug**
Provided OS X binary in 1.0.2.0 version is a Linux ELF binary 

**To Reproduce**
1. Go to https://github.com/KoenZomers/RingSnapshotDownload/releases/tag/1.0.2.0
2. Download the OS X version https://github.com/KoenZomers/RingSnapshotDownload/releases/download/1.0.2.0/osx-x64.zip
3. Unzip
4. xxd osx-x64/RingSnapshotDownload

The file is a Linux ELF binary and not a valid OS X binary.

**Comment by KoenZomers** [comment]
Hi @rogerheykoop. Can you give it a try with the [latest release](https://github.com/KoenZomers/RingSnapshotDownload/releases/latest)? I have now automated the creation process of the binaries, so it should not occur anymore.

**Comment by KoenZomers** [comment]
Closing as topic started has reported it to work now.
