### ISSUE TITLE
[FEATURE REQUEST] Linux ARM64 version

### ISSUE THREAD

**Issue by Sergong** [KoenZomers/RingSnapshotDownload#8]
**Is your feature request related to a problem? Please describe.**
First off, great work on the API and this wrapper for it!
Unfortunately the Linux ARM binary does not work on Raspberry Pi 4 with Ubuntu 20.04 without 32bit libraries installed (which I believe is the default).

**Describe the solution you'd like**
It would be great to have a Linux ARM64 version in addition to the ‘regular’ 32bit ARM version.

**Describe alternatives you've considered**
I have considered creating this myself using the source code but would be better to have this available on this repo.

**Additional context**

**Comment by KoenZomers** [comment]
Hey @Sergong, I've added it in the [latest release](https://github.com/KoenZomers/RingSnapshotDownload/releases). Have fun! :)
